# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 796ddb981372ea97c0d234e958a6abd2d9ec07dd01037426d7bff4edeb0fa014d238f8b174578ec2e1eee7623459dbe541782e88ca700d5faa8a12cb325be48c

test:
  secret_key_base: 8cd9c5e51bf258dc942b9e91e796a4662883663bc01f07f3919675d96563950878247325e82aaa54972a41f86dad8b69a0ad78afc7a1d381daa7ad7e100b0c54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
